#!/bin/bash

REPOS=(
    "/home/devid/.dotfiles"
    "/home/devid/synthesis"
)

BRANCH="master"

eval "$(/usr/bin/ssh-agent -s)"
/usr/bin/ssh-add ~/.ssh/cron_github

process_repo() {
    local REPO_PATH="$1"
    /usr/bin/echo "Processing repository at $REPO_PATH"

    cd "$REPO_PATH" || { /usr/bin/echo "Repository not found: $REPO_PATH"; return; }

    if ! /usr/bin/git rev-parse --is-inside-work-tree &>/dev/null; then
        /usr/bin/echo "Not a valid git repository: $REPO_PATH"
        return
    fi

    /usr/bin/git add .
    files_added=$(git status --porcelain -z | /usr/bin/grep -z "^A " | /usr/bin/awk -v RS='\0' '{print $2}' | /usr/bin/xargs -0 /usr/bin/echo)
    files_updated=$(git status --porcelain -z | /usr/bin/grep -z "^ M " | /usr/bin/awk -v RS='\0' '{print $2}' | /usr/bin/xargs -0 /usr/bin/echo)
    files_removed=$(git status --porcelain -z | /usr/bin/grep -z "^D " | /usr/bin/awk -v RS='\0' '{print $2}' | /usr/bin/xargs -0 /usr/bin/echo)

    if [[ -n "$files_added" || -n "$files_updated" || -n "$files_removed" ]]; then
        commit_message="$(/bin/date '+%d-%m-%y') CR0N says Added: ${files_added:-none}, Updated: ${files_updated:-none}, Removed: ${files_removed:-none}"
        /usr/bin/git commit -S -m "$commit_message"
    else
        /usr/bin/echo "No new changes to commit in $REPO_PATH."
    fi

    if /usr/bin/git status | /usr/bin/grep -q "Your branch is ahead"; then
        /usr/bin/echo "Pushing commits for $REPO_PATH..."
        /usr/bin/git push origin "$BRANCH"
    else
        /usr/bin/echo "Nothing to push for $REPO_PATH."
    fi
}

for REPO in "${REPOS[@]}"; do
    process_repo "$REPO"
done

/usr/bin/echo "All repositories processed."

