#!/bin/bash
STATE_FILE="/tmp/monitor_hotswap_state"
export DISPLAY=:0
export XAUTHORITY=/home/devid/.Xauthority

HDMI_STATUS=$(xrandr | grep "HDMI-1-0 connected")
RESOLUTION=$(xrandr | grep -A1 "HDMI-1-0 connected" | tail -n 1 | awk '{print $1}')

PREVIOUS_STATE=""
if [ -f $STATE_FILE ]; then
    PREVIOUS_STATE=$(cat $STATE_FILE)
fi

CURRENT_STATE="HDMI_STATUS=${HDMI_STATUS},RESOLUTION=${RESOLUTION}"
if [ "$CURRENT_STATE" == "$PREVIOUS_STATE" ]; then
    exit 0
fi

echo "$CURRENT_STATE" > $STATE_FILE
if [ -n "$HDMI_STATUS" ]; then
    case "$RESOLUTION" in
        1680x1050)
            ~/.config/xrandr/top_down_1680x1050.sh
            ;;
        1920x1080)
            ~/.config/xrandr/top_down_1920x1080.sh
            ;;
        *)
            ~/.config/xrandr/defaults.sh
            ;;
    esac
else
    ~/.config/xrandr/defaults.sh
    xrandr --output HDMI-1-0 --off
fi

