#!/bin/bash
function _img() { 
    if [[ -f $1 ]]; then 
        mpv --no-terminal --loop-file --image-display-duration=inf "$1" || {
            tmpfile="/tmp/$(basename "$1").mp4"
            ffmpeg -y -loop 1 -i "$1" -f lavfi -i anullsrc -shortest -vf format=yuv420p -t 5 "$tmpfile" && mpv "$tmpfile";
        }
    else 
        echo "Error: File '$1' not found."
    fi 
}


lt() {
	depth=${1:-2}
	exa -aT -L $depth --color=always --group-directories-first --icons
}


function ls() {
    local target="${1:-.}"
    if [ -d "$target" ]; then
        exa -al --color=always --group-directories-first --icons "$target"
    else
        command ls "$@"
    fi
}


cd() {
	if [ -z "$1" ]; then
		builtin cd
	else
		builtin cd "$1"
		num_elements=$(exa -al --color=always --group-directories-first | wc -l)
		if [ "$num_elements" -le 55 ]; then
			lt 1
		fi
	fi
}

_bytes() {
    if [ -z "$1" ]; then
        echo "Usage: random_clip <number_of_bytes>"
        return 1
    fi
    head -c "$1" /dev/urandom | base64 | xclip -selection clipboard
}
